apiVersion: apps/v1
kind: Deployment
metadata:
  #annotations:
  #  kompose.cmd: kompose convert -f docker-compose.yml
  #  kompose.version: 1.31.2 (a92241f79)
  #creationTimestamp: null
  #labels:
  #  io.kompose.service: notification-ms
  name: notification-ms
  namespace: ms-layer
  labels:
    app.kubernetes.io/created-by: eric-see
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      #io.kompose.service: notification-ms
      #app: notification-ms
      app.kubernetes.io/name: notification-ms
      app.kubernetes.io/instance: notification-ms
      app.kubernetes.io/component: service
  strategy:
    type: Recreate
  template:
    #metadata:
    #  annotations:
    #    kompose.cmd: kompose convert -f docker-compose.yml
    #    kompose.version: 1.31.2 (a92241f79)
    #  creationTimestamp: null
    #  labels:
    #    io.kompose.network/kompose-default: "true"
    #    io.kompose.service: notification-ms
    metadata:
      #labels:
      #  app: notification-ms
       labels:
        app.kubernetes.io/name: notification-ms
        app.kubernetes.io/instance: notification-ms
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: eric-see
    spec:
      containers:
        - env:
            - name: AMQP_URL
              #value: amqp://guest:guest@rabbitmq:5672
              value: amqp://guest:guest@rabbitmq.common-utils.svc.cluster.local:5672
            - name: DB_DATABASE
              value: event-driven_db
            - name: DB_HOST
              #value: postgres
              value: postgres.common-utils.svc.cluster.local
            - name: DB_PASSWORD
              value: S3cret
            - name: DB_USER
              value: event-driven-user
            - name: QUEUE
              value: event_driven
          image: ksericpro/notification-ms:2.0.0
          name: notification-ms
          imagePullPolicy: IfNotPresent
          ports:
             - name: http
               containerPort: 8001
               protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            successThreshold: 3
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/src
              name: notification-ms-claim0
      restartPolicy: Always
      volumes:
        - name: notification-ms-claim0
          persistentVolumeClaim:
            claimName: notification-ms-claim0
#status: {}
