apiVersion: v1
kind: Service
metadata:
  name: sillyworld-service
  namespace: ingress-nginx
spec:
  selector:
    app: sillyworld
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30009
  type: LoadBalancer