apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  kompose.cmd: kompose convert -f docker-compose.yml
  #  kompose.version: 1.31.2 (a92241f79)
  #creationTimestamp: null
  #labels:
  #  io.kompose.service: notification-ms
  name: notification-ms-service
  namespace: ingress-nginx
spec:
  selector:
    app: notification-ms
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30011
  type: LoadBalancer
  #selector:
  #  io.kompose.service: notification-ms
#status:
  #loadBalancer: {}
