# ./helm/kong/templates/echo/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-1
spec:
  ingressClassName: kong
  rules:
  - host: keycloak.com.au
    http:
      paths:
      - path: /test1
        pathType: Prefix
        backend:
          serviceName: echo
          servicePort: 80