apiVersion: v1
kind: Service
metadata:
  #annotations:
  #  kompose.cmd: kompose convert -f docker-compose.yml
  #  kompose.version: 1.31.2 (a92241f79)
  #creationTimestamp: null
  #labels:
  #  io.kompose.service: notification-ms
  labels:
    app.kubernetes.io/created-by: eric-see
    app.kubernetes.io/type: app
  name: notification-ms
  namespace: ms-layer
spec:
  selector:
    app: notification-ms
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8001
      nodePort: 30111
  type: LoadBalancer
  #type: NodePort
  #selector:
  #  io.kompose.service: notification-ms
#status:
  #loadBalancer: {}
