version: "3"

services:

  app:
    container_name: notification-ms
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-ms:alphine 
    volumes:
      - ./src:/app/src
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=event-driven-user
      - POSTGRES_DB=event-driven_db

networks:
  default:
    driver: bridge