apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
    app.kubernetes.io/created-by: eric-see
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
  namespace: common-utils
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 80
  selector:
    io.kompose.service: pgadmin
status:
  loadBalancer: {}
