apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 4
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: ksericpro/backend:1.1.0
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 8080