apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: ingress-nginx
spec:
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
  type: LoadBalancer