version: "3"

services:

  app:
    container_name: user-ms
    build:
      context: .
      dockerfile: Dockerfile
    image: user-ms:alphine 
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  default:
    driver: bridge